[package]
name = "pseudobash"
version = "0.9.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.40", features = ["derive"] }
lazy_static = "1.5.0"
libc = "0.2.175"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
